services:
  - type: web
    name: bitoki
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn app_prod:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: TRADE_MODE
        value: sandbox
      - key: DATABASE_URL
        fromDatabase:
          name: bitoki-db
          property: connectionString

databases:
  - name: bitoki-db
    plan: free
    databaseName: bitoki
    user: bitoki
