services:
  - type: web
    name: bitoki
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn app_prod:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: TRADE_MODE
        value: sandbox
      - key: DATABASE_URL
        fromDatabase:
          name: bitoki-db
          property: connectionString
      - key: MAIL_SERVER
        value: smtp.zoho.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USE_TLS
        value: true
      - key: MAIL_USE_SSL
        value: false
      - key: MAIL_USERNAME
        value: foundryai@getfoundryai.com
      - key: MAIL_PASSWORD
        value: Flindell1977@
      - key: MAIL_DEFAULT_SENDER
        value: foundryai@getfoundryai.com
      - key: WEBAUTHN_RP_ID
        value: bitoki.onrender.com
      - key: APP_URL
        value: https://bitoki.onrender.com

databases:
  - name: bitoki-db
    plan: free
    databaseName: bitoki
    user: bitoki
